### ISSUE TITLE
requirements.txt conflicts

### ISSUE THREAD

**Issue by bomtall** [Cadarn/PyData-Prefect-Workshop#1]
Hello, I am using a miniconda python 3.12 environment and I get the following issues when I try to pip install the requirements:

```
INFO: pip is looking at multiple versions of spacy to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 1) and -r requirements.txt (line 8) because these package versions have conflicting dependencies.

The conflict is caused by:
    prefect 2.19.4 depends on typer!=0.12.2, <0.13.0 and >=0.12.0
    spacy 3.7.2 depends on typer<0.10.0 and >=0.3.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Could you please advise what to do?

**Comment by FinnNk** [comment]
I have the same issue installing into a fresh python 3.12.2 environment (Apple silicon mac).

**Comment by Cadarn** [comment]
Hi,
Apologies for this I forgot that I'd had to find a workaround previously to this. I've now updated the spaCy version in the requirement.txt as they have recently release a fix. With spaCy==3.7.5 the Typer conflict shouldn't happen, but you might have to pip install it as I'm not sure it's available yet through conda channels
